---
# tasks file for powerstore_create_volume
- name: Include connection variables
  include_vars: ../powerstore_common/vars/main.yml

- name: Create stand-alone volume
  dellemc.powerstore.dellemc_powerstore_volume:
    array_ip: "{{ array_ip }}"
    verifycert: "{{ verifycert }}"
    user: "{{ user }}"
    password: "{{ password }}"
    vol_name: "{{ vol_name }}"
    size: 1
    cap_unit: "{{ cap_unit }}"
    state: 'present'
    description: "{{ vol_name }}"     
    performance_policy: "{{ performance_policy }}"
  register: result_vol
- name: Set Volume id to varaible
  set_fact:
    volume_details : "{{ result_vol }}"
